//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: bikesim/Assets/proto/simulation.proto
namespace pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BicyclePoseMessage")]
  public partial class BicyclePoseMessage : global::ProtoBuf.IExtensible
  {
    public BicyclePoseMessage() {}
    
    private uint _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _yaw;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"yaw", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float yaw
    {
      get { return _yaw; }
      set { _yaw = value; }
    }
    private float _roll;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"roll", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float roll
    {
      get { return _roll; }
      set { _roll = value; }
    }
    private float _pitch;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"pitch", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pitch
    {
      get { return _pitch; }
      set { _pitch = value; }
    }
    private float _steer;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"steer", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float steer
    {
      get { return _steer; }
      set { _steer = value; }
    }
    private float _rear_wheel;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"rear_wheel", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rear_wheel
    {
      get { return _rear_wheel; }
      set { _rear_wheel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SimulationMessage")]
  public partial class SimulationMessage : global::ProtoBuf.IExtensible
  {
    public SimulationMessage() {}
    
    private uint _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private FirmwareVersion _gitsha1 = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gitsha1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FirmwareVersion gitsha1
    {
      get { return _gitsha1; }
      set { _gitsha1 = value; }
    }
    private SensorMessage _sensors = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sensors", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SensorMessage sensors
    {
      get { return _sensors; }
      set { _sensors = value; }
    }
    private ActuatorMessage _actuators = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"actuators", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActuatorMessage actuators
    {
      get { return _actuators; }
      set { _actuators = value; }
    }
    private BicycleStateMessage _state = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BicycleStateMessage state
    {
      get { return _state; }
      set { _state = value; }
    }
    private BicycleInputMessage _input = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"input", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BicycleInputMessage input
    {
      get { return _input; }
      set { _input = value; }
    }
    private BicyclePoseMessage _pose = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"pose", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BicyclePoseMessage pose
    {
      get { return _pose; }
      set { _pose = value; }
    }
    private BicycleModelMessage _model = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"model", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BicycleModelMessage model
    {
      get { return _model; }
      set { _model = value; }
    }
    private BicycleKalmanMessage _kalman = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"kalman", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BicycleKalmanMessage kalman
    {
      get { return _kalman; }
      set { _kalman = value; }
    }
    private BicycleAuxiliaryStateMessage _auxiliary_state = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"auxiliary_state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BicycleAuxiliaryStateMessage auxiliary_state
    {
      get { return _auxiliary_state; }
      set { _auxiliary_state = value; }
    }
    private TimingMessage _timing = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"timing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TimingMessage timing
    {
      get { return _timing; }
      set { _timing = value; }
    }
    private float _feedback_torque = default(float);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"feedback_torque", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float feedback_torque
    {
      get { return _feedback_torque; }
      set { _feedback_torque = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FirmwareVersion")]
  public partial class FirmwareVersion : global::ProtoBuf.IExtensible
  {
    public FirmwareVersion() {}
    
    private byte[] _f;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"f", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] f
    {
      get { return _f; }
      set { _f = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BicycleStateMessage")]
  public partial class BicycleStateMessage : global::ProtoBuf.IExtensible
  {
    public BicycleStateMessage() {}
    
    private readonly global::System.Collections.Generic.List<float> _x = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(1, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> x
    {
      get { return _x; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BicycleAuxiliaryStateMessage")]
  public partial class BicycleAuxiliaryStateMessage : global::ProtoBuf.IExtensible
  {
    public BicycleAuxiliaryStateMessage() {}
    
    private readonly global::System.Collections.Generic.List<float> _x = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(1, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> x
    {
      get { return _x; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BicycleInputMessage")]
  public partial class BicycleInputMessage : global::ProtoBuf.IExtensible
  {
    public BicycleInputMessage() {}
    
    private readonly global::System.Collections.Generic.List<float> _u = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(1, Name=@"u", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> u
    {
      get { return _u; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SensorMessage")]
  public partial class SensorMessage : global::ProtoBuf.IExtensible
  {
    public SensorMessage() {}
    
    private uint _kistler_measured_torque;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"kistler_measured_torque", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint kistler_measured_torque
    {
      get { return _kistler_measured_torque; }
      set { _kistler_measured_torque = value; }
    }
    private uint _kollmorgen_actual_torque;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"kollmorgen_actual_torque", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint kollmorgen_actual_torque
    {
      get { return _kollmorgen_actual_torque; }
      set { _kollmorgen_actual_torque = value; }
    }
    private uint _steer_encoder_count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"steer_encoder_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint steer_encoder_count
    {
      get { return _steer_encoder_count; }
      set { _steer_encoder_count = value; }
    }
    private uint _rear_wheel_encoder_count = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rear_wheel_encoder_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rear_wheel_encoder_count
    {
      get { return _rear_wheel_encoder_count; }
      set { _rear_wheel_encoder_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActuatorMessage")]
  public partial class ActuatorMessage : global::ProtoBuf.IExtensible
  {
    public ActuatorMessage() {}
    
    private uint _kollmorgen_command_torque;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"kollmorgen_command_torque", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint kollmorgen_command_torque
    {
      get { return _kollmorgen_command_torque; }
      set { _kollmorgen_command_torque = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SymmetricStateMatrixMessage")]
  public partial class SymmetricStateMatrixMessage : global::ProtoBuf.IExtensible
  {
    public SymmetricStateMatrixMessage() {}
    
    private readonly global::System.Collections.Generic.List<float> _m = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(1, Name=@"m", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> m
    {
      get { return _m; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SymmetricOutputMatrixMessage")]
  public partial class SymmetricOutputMatrixMessage : global::ProtoBuf.IExtensible
  {
    public SymmetricOutputMatrixMessage() {}
    
    private readonly global::System.Collections.Generic.List<float> _m = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(1, Name=@"m", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> m
    {
      get { return _m; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KalmanGainMatrixMessage")]
  public partial class KalmanGainMatrixMessage : global::ProtoBuf.IExtensible
  {
    public KalmanGainMatrixMessage() {}
    
    private readonly global::System.Collections.Generic.List<float> _m = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(1, Name=@"m", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> m
    {
      get { return _m; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BicycleKalmanMessage")]
  public partial class BicycleKalmanMessage : global::ProtoBuf.IExtensible
  {
    public BicycleKalmanMessage() {}
    
    private BicycleStateMessage _state_estimate = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"state_estimate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BicycleStateMessage state_estimate
    {
      get { return _state_estimate; }
      set { _state_estimate = value; }
    }
    private SymmetricStateMatrixMessage _error_covariance = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"error_covariance", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SymmetricStateMatrixMessage error_covariance
    {
      get { return _error_covariance; }
      set { _error_covariance = value; }
    }
    private SymmetricStateMatrixMessage _process_noise_covariance = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"process_noise_covariance", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SymmetricStateMatrixMessage process_noise_covariance
    {
      get { return _process_noise_covariance; }
      set { _process_noise_covariance = value; }
    }
    private SymmetricOutputMatrixMessage _measurement_noise_covariance = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"measurement_noise_covariance", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SymmetricOutputMatrixMessage measurement_noise_covariance
    {
      get { return _measurement_noise_covariance; }
      set { _measurement_noise_covariance = value; }
    }
    private KalmanGainMatrixMessage _kalman_gain = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"kalman_gain", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public KalmanGainMatrixMessage kalman_gain
    {
      get { return _kalman_gain; }
      set { _kalman_gain = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SecondOrderMatrixMessage")]
  public partial class SecondOrderMatrixMessage : global::ProtoBuf.IExtensible
  {
    public SecondOrderMatrixMessage() {}
    
    private readonly global::System.Collections.Generic.List<float> _m = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(1, Name=@"m", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> m
    {
      get { return _m; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StateMatrixMessage")]
  public partial class StateMatrixMessage : global::ProtoBuf.IExtensible
  {
    public StateMatrixMessage() {}
    
    private readonly global::System.Collections.Generic.List<float> _m = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(1, Name=@"m", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> m
    {
      get { return _m; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InputMatrixMessage")]
  public partial class InputMatrixMessage : global::ProtoBuf.IExtensible
  {
    public InputMatrixMessage() {}
    
    private readonly global::System.Collections.Generic.List<float> _m = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(1, Name=@"m", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> m
    {
      get { return _m; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OutputMatrixMessage")]
  public partial class OutputMatrixMessage : global::ProtoBuf.IExtensible
  {
    public OutputMatrixMessage() {}
    
    private readonly global::System.Collections.Generic.List<float> _m = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(1, Name=@"m", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> m
    {
      get { return _m; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FeedthroughMatrixMessage")]
  public partial class FeedthroughMatrixMessage : global::ProtoBuf.IExtensible
  {
    public FeedthroughMatrixMessage() {}
    
    private readonly global::System.Collections.Generic.List<float> _m = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(1, Name=@"m", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> m
    {
      get { return _m; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BicycleModelMessage")]
  public partial class BicycleModelMessage : global::ProtoBuf.IExtensible
  {
    public BicycleModelMessage() {}
    
    private float _v = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"v", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float v
    {
      get { return _v; }
      set { _v = value; }
    }
    private float _dt = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dt", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float dt
    {
      get { return _dt; }
      set { _dt = value; }
    }
    private SecondOrderMatrixMessage _M = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"M", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SecondOrderMatrixMessage M
    {
      get { return _M; }
      set { _M = value; }
    }
    private SecondOrderMatrixMessage _C1 = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"C1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SecondOrderMatrixMessage C1
    {
      get { return _C1; }
      set { _C1 = value; }
    }
    private SecondOrderMatrixMessage _K0 = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"K0", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SecondOrderMatrixMessage K0
    {
      get { return _K0; }
      set { _K0 = value; }
    }
    private SecondOrderMatrixMessage _K2 = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"K2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SecondOrderMatrixMessage K2
    {
      get { return _K2; }
      set { _K2 = value; }
    }
    private StateMatrixMessage _A = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"A", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public StateMatrixMessage A
    {
      get { return _A; }
      set { _A = value; }
    }
    private InputMatrixMessage _B = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"B", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public InputMatrixMessage B
    {
      get { return _B; }
      set { _B = value; }
    }
    private OutputMatrixMessage _C = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"C", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OutputMatrixMessage C
    {
      get { return _C; }
      set { _C = value; }
    }
    private FeedthroughMatrixMessage _D = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"D", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FeedthroughMatrixMessage D
    {
      get { return _D; }
      set { _D = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimingMessage")]
  public partial class TimingMessage : global::ProtoBuf.IExtensible
  {
    public TimingMessage() {}
    
    private uint _computation = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"computation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint computation
    {
      get { return _computation; }
      set { _computation = value; }
    }
    private uint _transmission = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"transmission", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint transmission
    {
      get { return _transmission; }
      set { _transmission = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}